INSERT INTO `MusicSet` (`title`, `slug`, `soundcloudUrl`, `published`) VALUES
('Jam Session House 11_9_25', 'jam-session-house-11_9_25', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/57-jam-session-house-11_9_25&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Jam Session Never Dull Mood Vol 3', 'jam-session-never-dull-mood-vol-3', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/49-jam-session-never-dull-mood-vol-3&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Jam Session Progressive House', 'jam-session-progressive-house', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/31-jam-session-progressive-house&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Tutti Frutti Faster', 'tutti-frutti-faster', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/tutti-frutti-faster&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Jam Session Dance House', 'jam-session-dance-house', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/19-jam-session-dance-house&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Dark House Session Honey Dijon Mood', 'dark-house-session-honey-dijon-mood', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/51-dark-house-session-honey-dijon-mood&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('House Tech House Based On', 'house-tech-house-based-on', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/55-house-tech-house-based-on&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Twinsick Session', 'twinsick-session', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/54-twinsick-session&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Jam Session House 11_9_25 (2)', 'jam-session-house-11_9_25-2', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/57-jam-session-house-11_9_25&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1),
('Jam Session Never Dull Mood Vol 3 (2)', 'jam-session-never-dull-mood-vol-3-2', 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/jose-miguel-serra/49-jam-session-never-dull-mood-vol-3&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true', 1);
